name: test GO

on:
  push:
    branches: [ master ]

jobs:
  tets:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.21"


    # - name: Install dependencies
    #   run: go mod download 
    - name: Build
      run: go build -v
    - name: Test
      uses: robherley/go-test-action@v0
      with:
        moduleDirectory: '.'    
