name: test GO

on:
  push:
    branches: [ master ]

jobs:
  jest:
    name: jest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.21"


    - name: Build
      run: go build -v ./...    
    - name: Test
      uses: robherley/go-test-action@v0

